# Usando a versão do Node que você já está usando
FROM node:22-alpine

WORKDIR /app

# Copia arquivos de dependências
COPY package*.json ./
COPY prisma ./prisma/

# Instala dependências
RUN npm install

# Copia o restante do código
COPY . .

# Gera o Prisma Client
RUN npx prisma generate

# Build do TypeScript
RUN npm run build

# Comando para rodar o worker
CMD ["npm", "run", "start"]